// Auto-generated by the Webpack Config Generator
// http://localhost:3000

const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist/'),
    publicPath: 'dist/',
    filename: 'bundle.js'
  },
  resolve: { extensions: ['*', '.js'] }
};
